services:
  product-service:
    build:
      context: ./product-services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=product-db
      - DB_USER=root
      - DB_PASSWORD=Dev@root23
      - DB_NAME=productdb
    depends_on:
      - product-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=product-db", "--user=root", "--password=Dev@root23"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  product-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Dev@root23
      MYSQL_DATABASE: productdb
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=Dev@root23"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  product-db-data:
