services:
  main-app:
    build:
      context: ./main-app  # Path ke folder main app
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - product-service
      - cart-service
      - review-service
    environment:
      - HOSTNAME=main-app

  product-service:
    build:
      context: ./product-services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=product-db
      - DB_USER=root
      - DB_PASSWORD=Dev@root23
      - DB_NAME=productdb
    depends_on:
      - product-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=product-db", "--user=root", "--password=Dev@root23"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cart-service:
    build:
      context: ./cart-services
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=cart-db
      - DB_USER=postgres
      - DB_PASSWORD=Dev@root23
      - DB_NAME=cartdb
      - APP_ENV=docker
    depends_on:
      - cart-db
    healthcheck:
      test: ["CMD", "pg_isready", "--host=cart-db", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    command: bash -c "php artisan migrate && php -S 0.0.0.0:3002 -t public"

  review-service:
    build:
      context: ./review-services  
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://root:Dev@root23@review-db:27017/review_service
      - MONGO_HOST=review-db 
    depends_on:
      - review-db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  product-db:
    image: mysql:8.0
    environment:
      - DB_HOST=product-db
      - DB_USER=root
      - DB_PASSWORD=Dev@root23
      - DB_NAME=productdb
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=Dev@root23"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cart-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: Dev@root23
      POSTGRES_DB: cartdb
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  review-db:
    image: mongo:6.0
    container_name: review-db
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Dev@root23
    volumes:
      - review-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  product-db-data:
  cart-db-data:
  review-db-data:
